theme: minima
markdown: kramdown
title: Empirical Standards
description: Empirical standards for conducting and evaluating research in software engineering
header_pages:
  - tab_01_about.md
  - tab_02_tools.md
  - tab_03_standards.md
  - tab_04_supplements.md
  - tab_05_faq.md
  - tab_06_people.md
collections:
  team:
    output: true
