theme: minima
markdown: kramdown
title: SIGSOFT Empirical Standards
header_pages:
  - tab_01_about.md
  - tab_02_tools.md
  - tab_03_standards.md
  - tab_04_supplements.md
  - tab_05_faq.md
  - tab_06_people.md
collections:
  team:
    output: true
google_analytics: G-JFZW6XXB7T
